.TH build-kernel 8 "August 2021" "kernel-tools version 1.22"

.SH NAME
build-kernel \- Easily build a new kernel which source is located in /usr/src/linux from given or current working config file

.SH SYNOPSIS
.B build-kernel
[
.B OPTION
] [
.B DIRECTORY
|
.B FILE
]

.SH DESCRIPTION
For building a kernel, first select a kernel source in /usr/src/linux, use
.I "eselect kernel set"
or
.I "ln -sf /usr/src/LINUX-SRC-DIRECTORY /usr/src/linux"
.PP
A kernel's configuration file can be choosen with
.B OPTION
.I --current
or
.I --working
or by choosing a
.B DIRECTORY
or
.B FILE
\- If none is selected, current running kernel will be used (
.I /proc/config.gz
), if it's different than
.I /usr/src/linux/.config
, confirmation will be asked.
.PP
Script will first try to update config file using
.I make oldconfig
next it will ask for editing config file via
.I make menuconfig
after what it will build kernel and modules and install all.
.PP
If
.I genkernel
or
.I dracut
is used, it will also build initramfs image using wanted tool (
.R see
.BR CONFIGURATION
).
.PP
After what it will try to rebuild emerged modules for this kernel.
.PP
If
.I grub
is used, script will finally update Grub menu.

.SH OPTIONS
.TP
\-h, \-\-help
display a short help text
.TP
\-v, \-\-version
display current script version
.TP
\-c, \-\-current
tells script too use current
.I \.config
file located in 
.I /usr/src/linux
.TP
\-w, \-\-working
tells script too use current kernel's built-in configuration
.I /proc/config\.gz
.TP
\-\-(no)grub, \-\-grub=<0|1>
override script's configuration and update Grub bootloader (or not) when kernel is built
.TP
\-\-noinitramfs
override script's configuration and skip initramfs image generation
.TP
\-\-genkernel, \-\-dracut
override script's configuration and try to create initramfs image with named tool

.SH DIRECTORY
tells script to use .config file located in
.B DIRECTORY

.SH FILE
tells script to use
.B FILE
config file

.SH CONFIGURATION
Persistent script configuration is stored in
.I /etc/conf.d/build-kernel.cnf
.PP
Prefered way to edit configuration is to override it in user's
.I ~/.config/build-kernel.cnf
as it won't be erased by updates
.PP
Possible configuration values are
.TP
.B CONFIG_TOOL
=
.B 'menuconfig'
|
.B 'xconfig'
|
.B 'gconfig'
|
.B 'nconfig'

Choose tool to use for editing config file
.TP
.B GRUB
=
.B 0
|
.B 1

Updates (or not) Grub menu on endd of kernel's compilation
.TP
.B INITRAMFS
=
.B no
|
.B genkernel
|
.B dracut

Create (or not) an initramfs image with choosen tool

.SH EXIT STATUS
.TP
.B 0
build-kernel returns a zero exit status if it succeeds
.TP
.B 1
indicates that making kernel have failed
.TP
.B 2
indicates that installing kernel and modules have failed
.TP
.B 3
indicates that creating initramfs image have failed
.TP
.B 255
indicates an error in finding source directory and/or config file or an error in script arguments
